fix compilation on RHEL6
Including stdio.h when _XOPEN_SOURCE is defined, _GNU_SOURCE is not, and
we're using C++ makes gcc emit this error on RHEL6:

In file included from /home/cmccabe/kudu/src/util/errno.cc:14:
/usr/include/stdio.h:454: error: expected initializer before ‘throw’
/usr/include/stdio.h:510: error: expected initializer before ‘throw’

So just use strcpy instead.

Signed-off-by: Colin Patrick McCabe <cmccabe@cloudera.com>