[thirdparty] fix Postgres memset_s() build issue on macOS
This changelist adds an extra patch from PostgreSQL's upstream git repo
to address compilation error on macOS after the recent update in Kudu's
3rd-party to enable building with GCC 15 [2]:

  thirdparty/src/postgresql-17.2/src/port/explicit_bzero.c:22:9: error:
        call to undeclared function 'memset_s'; ISO C99 and later do not
        support implicit function declarations
        [-Wimplicit-function-declaration]
     22 |         (void) memset_s(buf, len, 0, len);

Also, it updates the CFLAGS used to build PostgreSQL: keeping the flags
compatible with GCC 7, it switches the default C standard mode
from C17 to C11, replacing -std=c17 with -std=c11.

[1] https://github.com/postgres/postgres/commit/12eee85e5
[2] https://github.com/apache/kudu/commit/2acbccb8c

Change-Id: I88651ddd056c90c02f65148905c61eb0f4e54f94
Reviewed-on: http://gerrit.cloudera.org:8080/24964
Tested-by: Kudu Jenkins
Reviewed-by: Zoltan Martonka <zmartonka@cloudera.com>