java: remove flaky TestServerInfo.testConstructorNotSlow
This test was added in commit 0b1adf1f6. At the time there was some concern
that the 500ms timeout could cause flakiness, but the reasoning was that the
InetAddress.getByName calls weren't going to do DNS lookups. However, I saw
the test timeout in precommit with the following stack trace:

  org.junit.runners.model.TestTimedOutException: test timed out after 500 milliseconds
	at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
	at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
	at java.io.File.exists(File.java:819)
	at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java:1245)
	at sun.misc.URLClassPath$FileLoader.findResource(URLClassPath.java:1212)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:188)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:569)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:567)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:566)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1096)
	at org.apache.log4j.helpers.Loader.getResource(Loader.java:110)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:107)
	at org.slf4j.impl.Log4jLoggerFactory.<init>(Log4jLoggerFactory.java:66)
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at org.apache.kudu.util.NetUtil.<clinit>(NetUtil.java:42)
	at org.apache.kudu.client.ServerInfo.<init>(ServerInfo.java:58)
	at org.apache.kudu.client.TestServerInfo.testConstructorNotSlow(TestServerInfo.java:35)

Per the trace, it can take over 500ms just to initialize the test and its
dependents. As such, I think it's flaky by design and should be removed.

Change-Id: Id7bbe47bc88e88d67ebdb199cf34723a4b69e57c
Reviewed-on: http://gerrit.cloudera.org:8080/11125
Reviewed-by: Andrew Wong <awong@cloudera.com>
Tested-by: Adar Dembo <adar@cloudera.com>