Fix C++ client API docs
This patch fixes C++ API doxygen comments so the build succeeds. It's
unclear when this broke exactly.

Running docs/support/scripts/make_site.sh with Doxygen 1.8.11 failed
with the below warning:

util/monotime.h:371: error: argument 'lhs' of command @param is not found in the argument list of kudu::MonoDelta::operator+(const MonoDelta &, const MonoDelta &) (warning treated as error, aborting now)

When Kudu 1.12.0 was released, the docs were generated with Doxygen
1.8.11, although it's possible that treating warnings as errors was
disabled for the release to work around this issue.

After upgrading to Doxygen 1.8.15 this warning disappeared, but a
different one surfaced:

common/partial_row.h:105: error: Member SetBool(const Slice &col_name, bool val) WARN_UNUSED_RESULT (function) of class KuduPartialRow is not documented. (warning treated as error, aborting now)

I disabled WARN_AS_ERROR temporarily only to discover several other
warnings. Some of them were due to Doxygen bugs solved by another update
to 1.8.19 in commit de31237, the rest manually by this commit.

Change-Id: I387be394d656a7614189148a39ff7dec76eb994d
Reviewed-on: http://gerrit.cloudera.org:8080/16372
Tested-by: Kudu Jenkins
Reviewed-by: Grant Henke <granthenke@apache.org>