kudu-lint: mess with link order
I couldn't build kudu-lint without this change. Got link errors like:

  /usr/lib/llvm-3.4/lib/libLLVMSupport.a(Signals.o): In function `llvm::sys::PrintStackTrace(_IO_FILE*)':
  (.text+0x6a5): undefined reference to `dladdr'

Which makes me think that the LLVM libraries depend on system ones, and thus
should be listed before them.

Change-Id: I8d9695bfdfd6e3545fde4485eb61bf173ccf7af0
Reviewed-on: http://gerrit.ent.cloudera.com:8080/2343
Reviewed-by: Todd Lipcon <todd@cloudera.com>
Tested-by: jenkins