KUDU-2099: drop Java 7 support
Two commits merged since 1.9 yield compilation errors when building with
JDK 10 or later:

  .../client/AuthzTokenCache.java:230: error: cannot find symbol
      List<RpcAndException> pendingRetries = retriesForTable.putIfAbsent(
                                                            ^
  symbol:   method putIfAbsent(String,List<RpcAndException>)
  location: variable retriesForTable of type Map<String,List<RpcAndException>>
  .../client/KuduScannerIterator.java:34: error: KuduScannerIterator is not abstract and does not override abstract method remove() in Iterator
  public class KuduScannerIterator implements Iterator<RowResult> {
         ^

The root cause is that with JDK 10, these two methods have been lifted out
of their respective classes and are now defined via default interface
implementations, but the compiler can't emit those implementations into
Java 7-compatible bytecode[1].

So we can either work around those two issues, or we can drop support for
Java 7. Let's see if there are any objections to the latter.

1. https://stackoverflow.com/a/23757061

Change-Id: I05fcea8bbc7b773f95429b324acd0b9d18a6e9f8
Reviewed-on: http://gerrit.cloudera.org:8080/12816
Tested-by: Kudu Jenkins
Reviewed-by: Andrew Wong <awong@cloudera.com>
Reviewed-by: Grant Henke <granthenke@apache.org>
Reviewed-by: Todd Lipcon <todd@apache.org>