Fix compilation on XCode 11
I recently upgraded my Mac to XCode 11 which now fails with:

…/kudu/src/kudu/consensus/quorum_util-test.cc:49:16: error: constexpr variable cannot have non-literal type 'const std::initializer_list<char>'
constexpr auto kHealthStatuses = { '?', '-', 'x', '+' };
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/initializer_list:59:28: note: 'initializer_list<char>' is not literal because it is not an aggregate and has no constexpr constructors other than copy or move constructors
class _LIBCPP_TEMPLATE_VIS initializer_list

This looks to be realted some ambiquity in compiler support for this syntax:
https://stackoverflow.com/questions/36863503/struct-is-non-literal-type/36863691

I fixed this by converting it to a const instead of a consexpr.

Change-Id: Iad3db5ac4d65fd9bdfa8f357b350f24d0e0d3ec0
Reviewed-on: http://gerrit.cloudera.org:8080/14343
Tested-by: Kudu Jenkins
Reviewed-by: Andrew Wong <awong@cloudera.com>