Implement KuduSession::Close()
Right now if the client were to call Close() on a kudu session we'd
get a compilation error as the method is declared but not defined.
This just implements a simple version that just does what it says
on the header.

Change-Id: I7d70d840df43a88b04d49e34fc565b08c49cb206
Reviewed-on: http://gerrit.sjc.cloudera.com:8080/6863
Reviewed-by: Adar Dembo <adar@cloudera.com>
Tested-by: jenkins