[gutil] add libunwind along with libglog to fix build
Since libglog depends on libunwind (at least on older Linux systems),
it's necessary to add libunwind into the list of libraries when
linking in libglog.  Otherwise, in case of a static linkage, there are
errors like below:

./../../lib/../src/kudu/util/CMakeFiles/kudu_util.dir/debug-util.cc.o: In function `PrimeLibunwind':
src/kudu/src/kudu/util/debug-util.cc:349: undefined reference to `_Ux86_64_getcontext'
src/kudu/src/kudu/util/debug-util.cc:350: undefined reference to `_ULx86_64_init_local'
../../../lib/../src/kudu/util/CMakeFiles/kudu_util.dir/debug-util.cc.o: In function `kudu::StackTrace::Collect(int)':
src/kudu/src/kudu/util/debug-util.cc:591: undefined reference to `_Ux86_64_getcontext'
src/kudu/src/kudu/util/debug-util.cc:592: undefined reference to `_ULx86_64_init_local'
src/kudu/src/kudu/util/debug-util.cc:607: undefined reference to `_ULx86_64_step'
src/kudu/src/kudu/util/debug-util.cc:598: undefined reference to `_ULx86_64_get_reg'
src/kudu/src/kudu/util/debug-util.cc:607: undefined reference to `_ULx86_64_step'
../../../../../thirdparty/installed/uninstrumented/lib/libglog.a(libglog_la-utilities.o): In function `GetStackTrace':
src/kudu/thirdparty/src/glog-0.3.5/src/stacktrace_libunwind-inl.h:65: undefined reference to `_Ux86_64_getcontext'
src/kudu/thirdparty/src/glog-0.3.5/src/stacktrace_libunwind-inl.h:66: undefined reference to `_ULx86_64_init_local'
src/kudu/thirdparty/src/glog-0.3.5/src/stacktrace_libunwind-inl.h:78: undefined reference to `_ULx86_64_step'
src/kudu/thirdparty/src/glog-0.3.5/src/stacktrace_libunwind-inl.h:70: undefined reference to `_ULx86_64_get_reg'
src/kudu/thirdparty/src/glog-0.3.5/src/stacktrace_libunwind-inl.h:78: undefined reference to `_ULx86_64_step'
collect2: error: ld returned 1 exit status

This is a follow-up for a8d088e11b8b901a91e4820dcfdca9537a1e801a: in
that changelist KUDU_BASE_LIBS were removed from the linkage
of libraries/binaries where libgutil was linked in (KUDU_BASE_LIBS
contains both libglog and libunwind).

Change-Id: Ia91824b257fbc41a442b484bbc5a5f926db708ec
Reviewed-on: http://gerrit.cloudera.org:8080/11327
Reviewed-by: Andrew Wong <awong@cloudera.com>
Tested-by: Kudu Jenkins