KUDU-2411: Exclude libz from binary jar on macOS
macOS ships with a version of libz in /usr/lib so we should use that
instead in order to avoid ABI incompatibility with system libraries.

This is to address the following error observed when someone with an
older macOS version built a binary jar and it was tested on a newer
macOS version:

  dyld: Symbol not found: _inflateValidate
    Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    Expected in: /private/var/folders/80/kr312hd50c16mf7k1xm0fnv80000gp/T/kudu-binary-jar4282159433165606863/kudu-binary-1.9.0-osx-x86_64/bin/../lib/libz.1.dylib
   in /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib

Change-Id: I2f0862cd949da1466704011a6f3517eb49418570
Reviewed-on: http://gerrit.cloudera.org:8080/12444
Reviewed-by: Grant Henke <granthenke@apache.org>
Tested-by: Grant Henke <granthenke@apache.org>
(cherry picked from commit 626938ed8b9a5bcfe2c1c4a6be44af81f1eafb6b)
Reviewed-on: http://gerrit.cloudera.org:8080/12448
Tested-by: Kudu Jenkins
Reviewed-by: Andrew Wong <awong@cloudera.com>