[tools] fix linking error and compilation warning
On some machines, when compiling with LLVM-6.0 (release configuration),
the following errors were generated:

diagnostics_log_parser.cc.o:
    src/kudu/tools/diagnostics_log_parser.h:45: multiple definition of
    `kudu::tools::RecordTypeToString(kudu::tools::RecordType)'
tool_action_diagnose.cc.o:
    src/kudu/tools/diagnostics_log_parser.h:45: first defined here

diagnostics_log_parser.cc.o: In function `operator<<':
    src/kudu/tools/diagnostics_log_parser.h:53: multiple definition of
    `kudu::tools::operator<<(std::ostream&, kudu::tools::RecordType)'
    src/kudu/tools/diagnostics_log_parser.h:53: first defined here

There was also a compilation warning:

src/kudu/tools/diagnostics_log_parser.cc:167:18:
    warning: expression result unused [-Wunused-value]
  DCHECK_NOTNULL(group);

This patch addresses the linkage error and the compilation warning.
It also has an extra petty update to move 'using' declarations outside
of the kudu::tools namespace scope.

This is a follow-up for 76bbdd4a0b6cdbbf6985504b3e6d0aa4b229b05a.

Change-Id: Iaa1ce72253e978e0aa0153993bec8562a4923e21
Reviewed-on: http://gerrit.cloudera.org:8080/10610
Reviewed-by: Andrew Wong <awong@cloudera.com>
Tested-by: Alexey Serbin <aserbin@cloudera.com>