[ranger] clarify error message from subprocess
Often times, we'll see error messages like the following:

org.apache.kudu.client.NonRecoverableException: unable to send message: Other end of pipe was closed
  at org.apache.kudu.client.KuduException.transformException(KuduException.java:110)
  at org.apache.kudu.client.KuduClient.joinAndHandleException(KuduClient.java:470)
  at org.apache.kudu.client.KuduClient.openTable(KuduClient.java:288)
  ...

with litle explanation of what pipe was closed, when really, it's always
the Ranger subprocess pipe. This patch adds that context so it's clear
to users that their pipe-related issues are Ranger client issues.

I tested this manually by running a Ranger test, killing the Ranger
client subprocess, and witnessing the following Kudu C++ client error
message:

End of file: Error creating table db.table on the master: Failed to execute Ranger client subprocess request: unable to send message: Other end of pipe was closed

Change-Id: I4a0fcd899439a822c6239494fedb0895adc046fd
Reviewed-on: http://gerrit.cloudera.org:8080/18067
Reviewed-by: Alexey Serbin <aserbin@cloudera.com>
Tested-by: Kudu Jenkins