[thirdparty] upgrade bison up to 3.8.2
This patch updates the bison library in Kudu's 3rd-party from 3.5.4 to
3.8.2 version.

The rationale behind the upgrade was getting the following build error
on macOS when building with clang 15.0.0 which comes with Xcode 15.3:

  kudu/thirdparty/src/bison-3.5.4/lib/obstack.c:351:31: error: incompatible function pointer types initializing 'void (*)(void) __attribute__((noreturn))' with an expression of type 'void (void)' [-Wincompatible-function-pointer-types]
  __attribute_noreturn__ void (*obstack_alloc_failed_handler) (void)
				^
  1 error generated.
  make[2]: *** [lib/libbison_a-obstack.o] Error 1

Change-Id: I93382dd06fcc86d34b5f63b02fb6e52859dcc558
Reviewed-on: http://gerrit.cloudera.org:8080/21192
Tested-by: Alexey Serbin <alexey@apache.org>
Reviewed-by: Abhishek Chennaka <achennaka@cloudera.com>
(cherry picked from commit 96a1770ad9f9be90fa9ce81eeb69561a18ca2da4)
Reviewed-on: http://gerrit.cloudera.org:8080/21786
Reviewed-by: Alexey Serbin <alexey@apache.org>
Tested-by: Abhishek Chennaka <achennaka@cloudera.com>