[thirdparty] stip more features from libcurl
It turned out that current configuration of libcurl in thirdparty
picks up IDN2 (support for international domain names) and extra
verification of cookies using PSL (Public Domain List) library,
if corresponding libraries are available on the build machine.
There aren't any known built-time or run-time use cases for these
features at this point, so it makes sense to remove them.

Explicitly configuring libcurl without these features helps to get
rid of linkage errors on macOS in case of RELEASE builds if
corresponding libraries are present:

  Undefined symbols for architecture x86_64:
    "_idn2_check_version", referenced from:
        _idnconvert_hostname in libcurl.a(libcurl_la-url.o)
        _curl_version in libcurl.a(libcurl_la-version.o)
        _curl_version_info in libcurl.a(libcurl_la-version.o)
    "_idn2_free", referenced from:
        _conn_free in libcurl.a(libcurl_la-url.o)
        _create_conn in libcurl.a(libcurl_la-url.o)
    "_idn2_lookup_ul", referenced from:
        _idnconvert_hostname in libcurl.a(libcurl_la-url.o)
    "_idn2_strerror", referenced from:
        _idnconvert_hostname in libcurl.a(libcurl_la-url.o)
    "_psl_builtin", referenced from:
        _Curl_psl_use in libcurl.a(libcurl_la-psl.o)
    "_psl_free", referenced from:
        _Curl_psl_destroy in libcurl.a(libcurl_la-psl.o)
        _Curl_psl_use in libcurl.a(libcurl_la-psl.o)
    "_psl_get_version", referenced from:
        _curl_version in libcurl.a(libcurl_la-version.o)
    "_psl_is_cookie_domain_acceptable", referenced from:
        _Curl_cookie_add in libcurl.a(libcurl_la-cookie.o)
    "_psl_latest", referenced from:
        _Curl_psl_use in libcurl.a(libcurl_la-psl.o)
  ld: symbol(s) not found for architecture x86_64

Change-Id: Iae1007773b45b0e9596b5a74d22930d4a107e508
Reviewed-on: http://gerrit.cloudera.org:8080/15195
Reviewed-by: Grant Henke <granthenke@apache.org>
Tested-by: Kudu Jenkins