[test] use full specification for RedoType elements
My follow-up patch hit a conflict of KuduWriteOperation and RedoType
enums in fuzz-itest.cc:

  src/kudu/integration-tests/fuzz-itest.cc:235:3:
  error: ‘INSERT’ conflicts with a previous declaration
     INSERT,
     ^~~~~~
  In file included from src/kudu/tablet/tablet_replica.h:42,
                   from src/kudu/integration-tests/fuzz-itest.cc:67:
  src/kudu/tablet/ops/write_op.h:66:3: note: previous declaration ‘kudu::tablet::WritePrivilegeType INSERT’
     INSERT,

This changelist addresses the issue.  I separated this change from the
follow-up patch for the ease of reviewing and tracking these changes
in the code.

There are no functional changes in this patch.

Change-Id: Id64eb45fd33bed84cb26d44151deda405547d24f
Reviewed-on: http://gerrit.cloudera.org:8080/17091
Reviewed-by: Andrew Wong <awong@cloudera.com>
Tested-by: Kudu Jenkins