Fix compilation error after ce0fcd4dd65a23aebf2601570e335c1b6ce2a0c9
This commit had a small semantic conflict with another commit that went
into master before it. This fixes the trivial issue.

Change-Id: I54f714d6f1eb2929784f0a2cf2e18a18c97ac980
Reviewed-on: http://gerrit.cloudera.org:8080/4331
Reviewed-by: Adar Dembo <adar@cloudera.com>
Tested-by: Todd Lipcon <todd@apache.org>