Added --without-des to the ./configure command for cyrus sasl
Cyrus Sasl requires DES to be available or the thridparty build fails with:
auth_getpwent.c:57: fatal error: des.h: No such file or directory
Adding --without-des to the configure string prevents it from failing.
NOTE that, from the docs, the only GSSAPI encryption available is DES, so
GSSAPI encryption will not be available.

Change-Id: I04ae5f0d164254acca0780db95b4ee4064d9b0d5
Reviewed-on: http://gerrit.ent.cloudera.com:8080/160
Reviewed-by: Michael Percy <mpercy@cloudera.com>
Reviewed-by: Todd Lipcon <todd@cloudera.com>
Tested-by: jenkins <kitchen-build@cloudera.com>