Include boost/thread/thread.hpp instead of boost/thread.hpp
This is trying to fix an issue seen on one of the centos6 build slaves,
where clang 3.2 is unhappy with boost 1.41:
/usr/include/boost/exception_ptr.hpp:41:5: error: exception specification of overriding function is more lax than base version

Since we don't need that part of the boost thread library for now,
just including the more specific dependency.