test_result_server: better handling for non-ASCII in logs
I was trying to diagnose a test failure whose log contained gdb stack
traces, and got this exception:

Traceback (most recent call last):
  File "/home/todd/flaky-test-server-env/lib/python2.6/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/todd/flaky-test-server-env/lib/python2.6/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/todd/flaky-test-server-env/lib/python2.6/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "./test_result_server.py", line 174, in diagnose
    return self.render_container(template.render(summary=summary, log_text=log_text))
  File "/home/todd/flaky-test-server-env/li
b/python2.6/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/todd/flaky-test-server-env/lib/python2.6/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 5, in top-level template code
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 3871577: ordinal not in range(128)

The docs for jinja2 say that it expects to receive unicode types, and I
think we're passing in strings. This should fix that.

Change-Id: Iac6da45ffe6c473dc985e60a4471ba708bae4610
Reviewed-on: http://gerrit.sjc.cloudera.com:8080/6272
Reviewed-by: Todd Lipcon <todd@cloudera.com>
Tested-by: jenkins