[java client] Improve how we start and stop processes
This patch adds a verification in BaseKuduTest that when we start a new process
that it's still alive a few hundreds of ms later. The log looks like this:

kudu.rpc.TestRowErrors  Time elapsed: 0.47 sec  <<< ERROR!
java.lang.Exception: We tried starting a process (kudu-master) but it exited with value=134
	at kudu.rpc.BaseKuduTest.configureAndStartProcess(BaseKuduTest.java:119)
	at kudu.rpc.BaseKuduTest.setUpBeforeClass(BaseKuduTest.java:68)
	at kudu.rpc.TestRowErrors.setUpBeforeClass(TestRowErrors.java:22)

This patch also adds another "finally" block in tearDownAfterClass() so that an exception coming
from d.join() won't leave us leaking a master and a TS.

Change-Id: I6c35cfdacc3e9f4de9ff48b4f54575c5ecfe757e
Reviewed-on: http://gerrit.sjc.cloudera.com:8080/4761
Reviewed-by: Adar Dembo <adar@cloudera.com>
Tested-by: jenkins