[codegen] fix build on macOS
This addresses linker error on macOS:

    void google::MakeCheckOpValueString<std::nullptr_t>(...), referenced from:
        ... google::MakeCheckOpString<std::nullptr_t, void*>(...) in jit_frame_manager.cc.o
  ld: symbol(s) not found for architecture x86_64

This is a follow-up to 0efbebd487e7d0c7f21ab0d5a91e0fa70046af83.

Change-Id: I00743d0a452ab5e33c3441cac4e06ff1bf58b7a6
Reviewed-on: http://gerrit.cloudera.org:8080/23943
Tested-by: Alexey Serbin <alexey@apache.org>
Reviewed-by: Abhishek Chennaka <achennaka@cloudera.com>
Reviewed-by: Marton Greber <greber.mx@gmail.com>
Reviewed-by: Zoltan Martonka <zmartonka@cloudera.com>
Reviewed-by: Zoltan Chovan <zchovan@cloudera.com>
(cherry picked from commit 514a3ff1a3b0ed912498a079ba73c7afcdd1a753)
Reviewed-on: http://gerrit.cloudera.org:8080/23961