url-coding: use standard stdint instead of boost
Not sure what's going on here, but maybe it'll help fix the following
breakage when building the Kudu client library in the Impala build:

Change-Id: I9b3bf141d717d05a8d35aea277246ecff925449e
17:02:18 In file included from /data/jenkins/workspace/generic-package-ubuntu64-14-04-impala/Kudu-Packaging-Kimpala-2015-03-26_16-44-33/impala-2.1.2+cdh5.3.2+0-1.cdh5.3.2.p0.3~trusty/Kudu/src/kudu/util/url-coding.cc:16:0:
17:02:18 /data/jenkins/workspace/generic-package-ubuntu64-14-04-impala/Kudu-Packaging-Kimpala-2015-03-26_16-44-33/impala-2.1.2+cdh5.3.2+0-1.cdh5.3.2.p0.3~trusty/Kudu/src/kudu/util/url-coding.h:31:34: error: ‘uint8_t’ was not declared in this scope
17:02:18  void UrlEncode(const std::vector<uint8_t>& in, std::string* out,
17:02:18                                   ^
17:02:18 /data/jenkins/workspace/generic-package-ubuntu64-14-04-impala/Kudu-Packaging-Kimpala-2015-03-26_16-44-33/impala-2.1.2+cdh5.3.2+0-1.cdh5.3.2.p0.3~trusty/Kudu/src/kudu/util/url-coding.h:31:34: note: suggested alternative:
17:02:18 In file included from /data/jenkins/workspace/generic-package-ubuntu64-14-04-impala/Kudu-Packaging-Kimpala-2015-03-26_16-44-33/impala-2.1.2+cdh5.3.2+0-1.cdh5.3.2.p0.3~trusty/Kudu/src/kudu/util/url-coding.h:21:0,
17:02:18                  from /data/jenkins/workspace/generic-package-ubuntu64-14-04-impala/Kudu-Packaging-Kimpala-2015-03-26_16-44-33/impala-2.1.2+cdh5.3.2+0-1.cdh5.3.2.p0.3~trusty/Kudu/src/kudu/util/url-coding.cc:16:
17:02:18 /usr/include/boost/cstdint.hpp:211:30: note:   ‘boost::uint8_t’
17:02:18       typedef unsigned char   uint8_t;
17:02:18                               ^
Reviewed-on: http://gerrit.sjc.cloudera.com:8080/6233
Tested-by: jenkins
Reviewed-by: Jean-Daniel Cryans <jdcryans@cloudera.com>