dist-test: improve error message when no tests run
This patch improves the error message displayed when no matching tests
are found to run.

Previous error message for the "loop" action:

../build-support/dist_test.py loop --num-instances 1024 -- bin/remote_ksck-test --gtest_filter=RemoteKsckTest.TestChecksumSnapshotLastingLongerThanAHM --stress-cpu-threads=16
isolate: at least one isolate file required
2019-03-26 13:24:19,260 ERROR: Failed to run isolate
Traceback (most recent call last):
  File "/home/mpercy/src/kudu/build-support/dist_test.py", line 606, in <module>
    main(sys.argv[1:])
  File "/home/mpercy/src/kudu/build-support/dist_test.py", line 601, in main
    args.func(p, args)
  File "/home/mpercy/src/kudu/build-support/dist_test.py", line 513, in loop_test
    run_isolate(staging)
  File "/home/mpercy/src/kudu/build-support/dist_test.py", line 396, in run_isolate
    '--'] + staging.gen_json_paths())
  File "/usr/local/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['isolate', 'batcharchive', '-isolate-server=http://isolate.cloudera.org:4242/', '-dump-json=/home/mpercy/src/kudu/build/isolate/dump.json', '--']' returned non-zero exit status 1

New error message:

../build-support/dist_test.py loop --num-instances 1024 -- bin/remote_ksck-test --gtest_filter=RemoteKsckTest.TestChecksumSnapshotLastingLongerThanAHM --stress-cpu-threads=16
Traceback (most recent call last):
  File "/home/mpercy/src/kudu/build-support/dist_test.py", line 608, in <module>
    main(sys.argv[1:])
  File "/home/mpercy/src/kudu/build-support/dist_test.py", line 603, in main
    args.func(p, args)
  File "/home/mpercy/src/kudu/build-support/dist_test.py", line 494, in loop_test
    raise Exception("No matching tests found for pattern %s" % tests_regex)
Exception: No matching tests found for pattern ^remote_ksck-test(\.[0-9]+)?$

Change-Id: If26dad45a8c75f773b36a1255b53b5dac006edf3
Reviewed-on: http://gerrit.cloudera.org:8080/12865
Tested-by: Kudu Jenkins
Reviewed-by: Adar Dembo <adar@cloudera.com>