[thirdparty] fix preflight check on macOS 10.13
With e432e637e changelist, the pre-flight check on my macOS HighSierra
faled while trying to rebuild thirdparty components:

  Checking for C++17 compiler support ...
  *** Unable to compile a simple c++17 program. Please use g++ 7.0 or higher. On CentOS 7 or RHEL 7 you must use the devtoolset. See docs/installation.adoc for more info.
  Compilation failed: <stdin>:5:19: error: call to unavailable member function 'value': introduced in macOS 10.14
          return oi.value();

This patch fixes the issue, switching from std::optional<T>::value()
to std::optional::operator*() in the pre-flight C++17 check.

For posterity, the environment was:

  $ sw_vers
  ProductName:	Mac OS X
  ProductVersion:	10.13.6
  BuildVersion:	17G14042

  $ clang --version
  Apple LLVM version 10.0.0 (clang-1000.11.45.5)
  Target: x86_64-apple-darwin17.7.0
  Thread model: posix
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Change-Id: I5c6f8b13f141d46d745011cd00f65d3440ab9016
Reviewed-on: http://gerrit.cloudera.org:8080/16798
Reviewed-by: Grant Henke <granthenke@apache.org>
Tested-by: Alexey Serbin <aserbin@cloudera.com>