CapturingLogAppender: synchronize access to captured log text
I have no explanation for how this could happen, but the test failure I'm
looking at speaks for itself:

  1) testSessionOnceClosed(org.apache.kudu.client.TestKuduClient)
  java.lang.StringIndexOutOfBoundsException: String index out of range: 419
	at java.lang.String.<init>(String.java:205)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at org.apache.kudu.test.CapturingLogAppender.getAppendedText(CapturingLogAppender.java:72)
	at org.apache.kudu.client.TestKuduClient.testSessionOnceClosed(TestKuduClient.java:1231)

Change-Id: I84a5d0775cba5aa1d9df5484b5e9e621c908d42d
Reviewed-on: http://gerrit.cloudera.org:8080/14431
Reviewed-by: Greg Solovyev <gsolovyev@cloudera.com>
Tested-by: Kudu Jenkins
Reviewed-by: Grant Henke <granthenke@apache.org>
(cherry picked from commit 0894eba26380036d6d6d59c29c3efc5b3a817641)
Reviewed-on: http://gerrit.cloudera.org:8080/14467