python: add workaround for multiprocessing atexit hook on py2.6
23cbc63387c066eff513a5a7c3a66a01ff491e79 had removed the dependency on
multiprocessing. However, this exposed a python 2.6 bug[1] which caused the
following output at the end of any test run:

  Error in atexit._run_exitfuncs:
  Traceback (most recent call last):
    File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
      func(*targs, **kargs)
    File "/usr/lib64/python2.6/multiprocessing/util.py", line 258, in _exit_function
      info('process shutting down')
  TypeError: 'NoneType' object is not callable
  Error in sys.exitfunc:
  Traceback (most recent call last):
    File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
      func(*targs, **kargs)
    File "/usr/lib64/python2.6/multiprocessing/util.py", line 258, in _exit_function
      info('process shutting down')
  TypeError: 'NoneType' object is not callable

This patch adds a workaround for the issue as suggested in the bug report.

[1] http://bugs.python.org/issue15881

Change-Id: I72dd0b8cb91ef6e4099b57792d95cfddec31eae1
Reviewed-on: http://gerrit.cloudera.org:8080/5410
Tested-by: Kudu Jenkins
Reviewed-by: Jordan Birdsell <jtbirdsell@apache.org>