build: tserver_service should depend on tserver_proto
Should fix a build failure:

Change-Id: I0fab924d4a9b1c42a9dfd6d141fc1ccfe1b9fc2e
14:33:46  /var/lib/jenkins/workspace/kudu-test/BUILD_TYPE/ASAN/label/centos6-kudu/src/tserver/tserver_service.pb.h:27:10: fatal error: 'tserver/tserver.pb.h' file not found
14:33:46  #include "tserver/tserver.pb.h"
Reviewed-on: http://gerrit.ent.cloudera.com:8080/1482
Reviewed-by: Matteo Bertozzi <matteo.bertozzi@cloudera.com>
Reviewed-by: David Alves <david.alves@cloudera.com>
Tested-by: jenkins