sasl: change sasl path flag to be kudu-specific
Impala uses the same sasl_path gflag. When we link the client into Impala, this
causes a duplicate symbol error. This patch prefixes it to be krpc-specific to
avoid this conflict.

Change-Id: Ie2d5e03f3d1576fd79f490953ffe51bf134cc2cf
Reviewed-on: http://gerrit.ent.cloudera.com:8080/2791
Tested-by: jenkins
Reviewed-by: Michael Percy <mpercy@cloudera.com>