Revert "gutil: stop supporting AMD Opteron K8"
This reverts commit b5004e1886eb96839ec120da582f0a06ce869db2.

This change broke the release build on el6:

../../../lib/libgutil.a(atomicops-internals-x86.cc.o): In function `AtomicOps_x86CPUFeaturesInit()':
<src/kudu/gutil/atomicops-internals-x86.cc>:122: multiple definition of `AtomicOps_Internalx86CPUFeatures'
../../../../../thirdparty/installed/uninstrumented/lib64/libtcmalloc.a(atomicops-internals-x86.o):(.bss+0x0): first defined here
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld: Warning: size of symbol `AtomicOps_Internalx86CPUFeatures' changed from 3 in ../../../../../thirdparty/installed/uninstrumented/lib64/libtcmalloc.a(atomicops-internals-x86.o) to 2 in ../../../lib/libgutil.a(atomicops-internals-x86.cc.o)

Change-Id: I898fe74cf80b0f91f1c88700572b07e131227901
Reviewed-on: http://gerrit.cloudera.org:8080/6676
Tested-by: Kudu Jenkins
Reviewed-by: Adar Dembo <adar@cloudera.com>