KUDU-911: fix parallel build when NO_TESTS=1
Mike Yoder ran into the following build breakage:

[ 51%] Building CXX object src/kudu/server/CMakeFiles/server_base_proto.dir/server_base.service.cc.o
In file included from /home/myoder/work/kudu/src/kudu/server/server_base.service.cc:5:
/home/myoder/work/kudu/src/kudu/server/server_base.service.h:11:36: error: kudu/rpc/rpc_header.pb.h: No such file or directory
In file included from /home/myoder/work/kudu/src/kudu/server/server_base.service.cc:9:
/home/myoder/work/kudu/src/kudu/rpc/inbound_call.h:91: error: ‘ErrorStatusPB’ has not been declared
/home/myoder/work/kudu/src/kudu/rpc/inbound_call.h:91: error: expected ‘,’ or ‘...’ before ‘error_code’
/home/myoder/work/kudu/src/kudu/rpc/inbound_call.h:101: error: ‘ErrorStatusPB’ has not been declared
/home/myoder/work/kudu/src/kudu/rpc/inbound_call.h:165: error: ‘RequestHeader’ does not name a type
/home/myoder/work/kudu/src/kudu/rpc/inbound_call.h: In member function ‘const int32_t kudu::rpc::InboundCall::call_id() const’:
/home/myoder/work/kudu/src/kudu/rpc/inbound_call.h:74: error: ‘header_’ was not declared in this scope
make[2]: *** [src/kudu/server/CMakeFiles/server_base_proto.dir/server_base.service.cc.o] Error 1
make[1]: *** [src/kudu/server/CMakeFiles/server_base_proto.dir/all] Error 2
make: *** [all] Error 2

The output shows that the server_base_proto cmake target depends on the
rpc_header_proto target, yet that dependency isn't expressed in cmake. More
generally, any target depending on the output of KRPC_GENERATE() needs to
also depend on the krpc and rpc_header_proto targets. The former already
depends on the latter, but I think it's more robust for targets to list all
of their direct dependents.

I still don't know why this only happens with NO_TESTS=1.

Change-Id: Ib91ac50e123c6e22b6a366da166284242ba545a1
Reviewed-on: http://gerrit.sjc.cloudera.com:8080/7286
Tested-by: Adar Dembo <adar@cloudera.com>
Reviewed-by: Todd Lipcon <todd@cloudera.com>