util: fix test compilation failures when building with gcc5
Both env-test and env_util-test fail to build with gcc5. The error messages
look like this:

  /home/adar/Source/kudu/src/kudu/util/env_util-test.cc: In lambda function:
  /home/adar/Source/kudu/src/kudu/util/env_util-test.cc:66:71: error: label 'gtest_label_testnofatal_68' used but not defined
  /home/adar/Source/kudu/src/kudu/util/env_util-test.cc:66:108: warning: label 'gtest_label_testnofatal_74' defined but not used [-Wunused-label]
  /home/adar/Source/kudu/src/kudu/util/env_util-test.cc: In member function 'virtual void kudu::env_util::EnvUtilTest_TestDiskSpaceCheck_Test::TestBody()':
  /home/adar/Source/kudu/src/kudu/util/env_util-test.cc:66:71: error: label 'gtest_label_testnofatal_72' used but not defined
  /home/adar/Source/kudu/src/kudu/util/env_util-test.cc:66:108: warning: label 'gtest_label_testnofatal_74' defined but not used [-Wunused-label]
  src/kudu/util/CMakeFiles/env_util-test.dir/build.make:62: recipe for target 'src/kudu/util/CMakeFiles/env_util-test.dir/env_util-test.cc.o' failed
  make[2]: *** [src/kudu/util/CMakeFiles/env_util-test.dir/env_util-test.cc.o] Error 1
  CMakeFiles/Makefile2:17400: recipe for target 'src/kudu/util/CMakeFiles/env_util-test.dir/all' failed
  make[1]: *** [src/kudu/util/CMakeFiles/env_util-test.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....

I thought maybe it was due to the NO_FATALS() nesting so I removed the inner
calls, but that didn't work. Removing the NO_FATALS() surrounding the
AssertEventually() calls does work, however.

Change-Id: I93b4b9a4e1d545144a0f82c0839ed6c445a7aec1
Reviewed-on: http://gerrit.cloudera.org:8080/6354
Tested-by: Kudu Jenkins
Reviewed-by: Mike Percy <mpercy@apache.org>
(cherry picked from commit 7034bffc1c851024759c8d6f644ee48bb43a1d67)
Reviewed-on: http://gerrit.cloudera.org:8080/6357
Reviewed-by: Adar Dembo <adar@cloudera.com>