master: add missing RPC dependency
The master library should be built after the rpc_header_proto library to
avoid this include error:

In file included from
/home/cmccabe/src/kudu/src/master/master.service.cc:5:
/home/cmccabe/src/kudu/src/master/master.service.h:11:10: fatal error:
'rpc/rpc_header.pb.h' file not found

Using make -j 8 hides this error because this results in the rpc/
directory usually getting built early enough.

Change-Id: I5f0c4c9f6a4a65a74ffc07bf48172c2a3e254929
Reviewed-on: http://gerrit.ent.cloudera.com:8080/2198
Tested-by: jenkins
Reviewed-by: Todd Lipcon <todd@cloudera.com>