[thirdparty] Fix LLVM build on macOS with Xcode 12
After upgrading Xcode I started seeing failures when building
thirdparty. An example is below. It looks like the issue
stems from a change in the default architecture to include
arm64. Full details on the issue can be seen here:
https://gitlab.kitware.com/cmake/cmake/-/issues/20893

To work around this issue this patch sets
`-DCMAKE_OSX_ARCHITECTURES="x86_64”` in the
LLVM build.

Example failure log:
ld: warning: building for iOS, but linking in .tbd file (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.0.sdk/usr/lib/system/libsystem_coreservices.tbd) built for iOS Simulator
…
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/ghenke/Source/kudu/thirdparty/build/llvm-9.0.0/lib/libclang_rt.builtins_arm64_ios.a and /Users/ghenke/Source/kudu/thirdparty/build/llvm-9.0.0/lib/libclang_rt.builtins_arm64_iossim.a have the same architectures (arm64) and can't be in the same fat output file

Change-Id: I0e7808fcd92227cd83b35f5bf1b9320c7887b603
Reviewed-on: http://gerrit.cloudera.org:8080/16520
Reviewed-by: Alexey Serbin <aserbin@cloudera.com>
Tested-by: Kudu Jenkins