[util] fixed env_util-test.cc compilation on OS X
The prior version failed to compile on OS X with clang version 3.9.0
(branches/release_39 277311) with error messaged containing:

/opt/local/libexec/llvm-3.9/bin/../include/c++/v1/algorithm:2643:1:
note:
  candidate template ignored: deduced conflicting types for parameter
  '_Tp' ('long' vs. 'long long')
max(const _Tp& __a, const _Tp& __b)
^
/opt/local/libexec/llvm-3.9/bin/../include/c++/v1/algorithm:2653:1:
note:
  candidate template ignored: could not match
    'initializer_list<type-parameter-0-0>' against 'long'
max(initializer_list<_Tp> __t, _Compare __comp)
^

Change-Id: I0ce139c9896a969d51bfcaeabdf6133287c3a897
Reviewed-on: http://gerrit.cloudera.org:8080/6282
Reviewed-by: Mike Percy <mpercy@apache.org>
Tested-by: Kudu Jenkins
(cherry picked from commit 97831eadf1511449daebe25d3431472b55e3c21c)
Reviewed-on: http://gerrit.cloudera.org:8080/6351
Reviewed-by: Jean-Daniel Cryans <jdcryans@apache.org>
Reviewed-by: Alexey Serbin <aserbin@cloudera.com>