[clock] fixed link error on OS X
kudu_common is needed to link the clock library, otherwise the following
error is output on OS X:

  Undefined symbols for architecture x86_64:
    "kudu::Timestamp::kInvalidTimestamp", referenced from:
        kudu::Timestamp::Timestamp() in hybrid_clock.cc.o
        kudu::clock::LogicalClock::Update(kudu::Timestamp const&) \
            in logical_clock.cc.o
    "kudu::Timestamp::ToUint64() const", referenced from:
        kudu::clock::HybridClock::NowForMetrics() in hybrid_clock.cc.o
        kudu::clock::LogicalClock::Stringify(kudu::Timestamp) \
            in logical_clock.cc.o
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 \
      (use -v to see invocation)

Change-Id: I5e5442333fb667b50aca2f8229e223d44edffd14
Reviewed-on: http://gerrit.cloudera.org:8080/7578
Reviewed-by: Adar Dembo <adar@cloudera.com>
Tested-by: Kudu Jenkins