arena: fix alignment of NewObject<> results, use variadic template
This makes two fixes to Arena<>::NewObject<>:

* Ensures that the returned object has the proper alignment required by
  the type being allocated. This fixes spurious leak warnings if the
  leak checker is run while there is a live object allocated from an
  arena which has pointers pointing out it. I hit this issue with a
  later patch in this same patch series which changes RowOp to be
  arena-allocated.

* Use C++11 variadic templates instead of multiple definitions for
  different parameter list lengths.

Change-Id: Idad12bee02eebf58bf8d545812a7d161bb829b71
Reviewed-on: http://gerrit.cloudera.org:8080/6492
Reviewed-by: Adar Dembo <adar@cloudera.com>
Tested-by: Todd Lipcon <todd@apache.org>