[util] added zlib as dependency for libcurl
After switching to libcurl from the thirdparty but prior to this patch,
the standard linker on CentOS6 would output errors like below when
building Kudu in RELEASE configuration:

  devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ld:
     thirdparty/installed/uninstrumented/lib/libcurl.a(libcurl_la-content_encoding.o):
	 undefined reference to symbol 'inflateInit2_'
  //lib64/libz.so.1: error adding symbols: DSO missing from command line
  collect2: error: ld returned 1 exit status

This is a follow-up to 5c610bf40543feca7ed934e9fe1ebbbcccd6c265.

Change-Id: I76ed772845a7e7a00b0ee023dfac51595af383ca
Reviewed-on: http://gerrit.cloudera.org:8080/15200
Reviewed-by: Adar Dembo <adar@cloudera.com>
Tested-by: Kudu Jenkins