[build] Fix LLVM build on Xcode 12.2
When building with the latest Xcode version (12.2) I found that the LLVM
build failed to build `sanitizer_platform_limits_posix.cpp` due to the `stat64`
type missing. Given we don’t need the sanitizers, I disabled building them
to work around the issue.

Example error message:
kudu/thirdparty/src/llvm-9.0.0.src/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:169:31: error: invalid application of 'sizeof' to an incomplete type 'struct stat64'
  unsigned struct_stat64_sz = sizeof(struct stat64);

Change-Id: I17ea2de460aac4142469c95af201b17554c4f751
Reviewed-on: http://gerrit.cloudera.org:8080/16746
Reviewed-by: Alexey Serbin <aserbin@cloudera.com>
Reviewed-by: Andrew Wong <awong@cloudera.com>
Tested-by: Kudu Jenkins