Lazily seek iterators in CFileSet.
This solves two major issues seen when testing Impala on a tablet with ~700
rowsets:

1) The first query on a cold cache consistently timed out its first Scan() RPC.
Looking at stacks shows that the server was spending several seconds calling
SeekToOrdinal(0) for every column iterator under the UnionIterator. Since
UnionIterator::Init() inits all underlying iterators, all of this cost was
being paid up front in the first RPC, rather than being spread out as the
scanner traversed from rowset to rowset in the union.

2) A query like "SELECT * from twitter limit 5;" always timed out its first
Scan() RPC for a similar reason: even though we only needed rows from the first
rowset, we were seeking every rowset.

This also gives an improvement in entirely avoiding seeking into a cfile if
predicates fail for all rows in that rowset (eg SELECT * WHERE <very selective
predicate>). This improvement is reflected in the updated unit test.

Before:
  [localhost:21000] > select * from twitter limit 5;
  Query: select * from twitter limit 5
  Query finished, fetching results ...
  ERROR: Runtime error: Call timed out

After:
  [localhost:21000] > select * from twitter limit 5;
  Query: select * from twitter limit 5
  Query finished, fetching results ...
  ... <results elided>
  Returned 5 row(s) in 0.20s

Change-Id: I20d06b0301f7ddfc7ae7013f02589a6f4ae43ca7
Reviewed-on: http://gerrit.ent.cloudera.com:8080/244
Tested-by: jenkins <kitchen-build@cloudera.com>
Reviewed-by: Todd Lipcon <todd@cloudera.com>