Bump Sentry version
The motivation is to get access to SENTRY-2471, which includes a fix for
syncing Sentry privilege changes upon table renaming even for tables
without HDFS path information. SENTRY-2471 has not been released yet,
so the new Sentry version is based on the latest commit of the master
branch.

Note that after bumping the Sentry version, the hms tests start to fail
with:
java.lang.UnsatisfiedLinkError: org.apache.hadoop.io.nativeio.NativeIO$POSIX.stat
(Ljava/lang/String;)Lorg/apache/hadoop/io/nativeio/NativeIO$POSIX$Stat;
  at org.apache.hadoop.io.nativeio.NativeIO$POSIX.stat(Native Method)
  at org.apache.hadoop.io.nativeio.NativeIO$POSIX.getStat(NativeIO.java:451)
This is due to hadoop 3.1.1 (SENTRY-2329) from Sentry package is loaded
into the HMS classpath. Since we have no reasons to use hadoop jars in
Sentry package, we can safely remove them.

Change-Id: I13f05345d2e6dcdadd74503d0d4524947b137d43
Reviewed-on: http://gerrit.cloudera.org:8080/13059
Reviewed-by: Adar Dembo <adar@cloudera.com>
Tested-by: Hao Hao <hao.hao@cloudera.com>
Reviewed-by: Andrew Wong <awong@cloudera.com>
Tested-by: Kudu Jenkins
Reviewed-by: Alexey Serbin <aserbin@cloudera.com>