[consensus] fix linkage failure on macOS
A prior patch implementing KUDU-1973 has introduced DCHECK_EQ()
that wouldn't compile on macOS with clang, even if it completes
successfully on Linux.  I didn't try to find the difference in how
the glog in 3rd-party is built, but simply replaced DCHECK_EQ()
with equivalent DCHECK() and now build passes on macOS as well.

Before this patch, building the project on macOS would fail with an
error like below:

Undefined symbols for architecture x86_64:
  "void google::MakeCheckOpValueString<std::nullptr_t>(std::__1::basic_ostream<char, std::__1::char_traits<char>>*, std::nullptr_t const&)", referenced from:
      std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>* google::MakeCheckOpString<std::nullptr_t, std::__1::shared_ptr<kudu::rpc::PeriodicTimer>>(std::nullptr_t const&, std::__1::shared_ptr<kudu::rpc::PeriodicTimer> const&, char const*) in multi_raft_batcher.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

[1] https://github.com/apache/kudu/commit/4999c30d1

Change-Id: I26d0b4c1149f2df92e0f8654f7dba654fa6e281d
Reviewed-on: http://gerrit.cloudera.org:8080/23476
Reviewed-by: Zoltan Martonka <zmartonka@cloudera.com>
Tested-by: Alexey Serbin <alexey@apache.org>
Reviewed-by: Abhishek Chennaka <achennaka@cloudera.com>