Fix python client build failure
Fix an error when install python client:
"""
running build_ext
building 'kudu.client' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/xxx/src -I/xxx/build/latest/src -I/usr/include/python3.6m -c kudu/client.cpp -o build/temp.linux-x86_64-3.6/kudu/client.o
kudu/client.cpp: In function 'int __pyx_pymod_exec_client(PyObject*)':
kudu/client.cpp:49497:142: error: 'kudu::client::KuduClientBuilder::EncryptionPolicy' is not a class or namespace
   __pyx_t_7 = __Pyx_PyInt_From_enum____kudu_3a__3a_client_3a__3a_KuduClientBuilder_3a__3a_EncryptionPolicy( kudu::client::KuduClientBuilder::EncryptionPolicy::OPTIONAL); if (unlikely(!__pyx_t_7)) __PYX_ERR(0, 78, __pyx_L1_error)
                                                                                                                                              ^
"""

Change-Id: I450b723707666b449031c7e9e9f2eacc71661001
Reviewed-on: http://gerrit.cloudera.org:8080/20451
Tested-by: Alexey Serbin <alexey@apache.org>
Reviewed-by: Alexey Serbin <alexey@apache.org>
Reviewed-by: Marton Greber <greber.mx@gmail.com>
Reviewed-by: KeDeng <kdeng.ke@gmail.com>
(cherry picked from commit b030c7ba02b199a73289a72bb5a06d76a9f58571)
Reviewed-on: http://gerrit.cloudera.org:8080/20456
Tested-by: Yingchun Lai <laiyingchun@apache.org>