python: work around pip 7.1.1 version check change
One of the changes in pip 7.1.1 was "Move the pip version check until after
any installs have been performed, thus removing the extraneous warning when
upgrading pip." I don't know what that means, but I do know that pip now
raises an exception when installing requirements on el6, either just after
uninstalling el6's old setuptools, or after installing the new one. I've
attached the stack trace at the end of this commit message.

The fix is simple: disable the version check during the pip call. We don't
need it anyway as we just explicitly upgraded pip. I filed
https://github.com/pypa/pip/issues/3045 upstream.

Installing collected packages: cython, nose, setuptools
  Running setup.py install for cython
  Found existing installation: setuptools 0.6rc11
    Uninstalling setuptools-0.6rc11:
      Successfully uninstalled setuptools-0.6rc11
Successfully installed cython nose setuptools
Traceback (most recent call last):
  File "/home/adar/kudu/python/test_environment/bin/pip", line 8, in <module>
    load_entry_point('pip==7.1.1', 'console_scripts', 'pip')()
  File "/home/adar/kudu/python/test_environment/lib/python2.6/site-packages/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/home/adar/kudu/python/test_environment/lib/python2.6/site-packages/pip/basecommand.py", line 248, in main
    pip_version_check(session)
  File "/home/adar/kudu/python/test_environment/lib/python2.6/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    pip_version = packaging_version.parse(get_installed_version('pip'))
  File "/home/adar/kudu/python/test_environment/lib/python2.6/site-packages/pip/utils/__init__.py", line 858, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/home/adar/kudu/python/test_environment/lib/python2.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 629, in __init__
    self.add_entry(entry)
  File "/home/adar/kudu/python/test_environment/lib/python2.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 685, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/adar/kudu/python/test_environment/lib/python2.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2075, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/home/adar/kudu/python/test_environment/lib/python2.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1605, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/home/adar/kudu/python/test_environment/lib/python2.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1963, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/home/adar/kudu/python/test_environment/lib/python2.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1843, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/home/adar/kudu/python/test_environment/lib/python2.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1783, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/home/adar/kudu/python/test_environment/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg'

Change-Id: I1247eec568c0a8ece8a1ad6fee389f92f6d13831
Reviewed-on: http://gerrit.sjc.cloudera.com:8080/7558
Tested-by: jenkins
Reviewed-by: Todd Lipcon <todd@cloudera.com>