python: fix Python 3.4 based tests
Pip released 19.0 recently and tests based on Python 3.4 started to fail. In
addition, Python 3.4 will no longer be supported beginning with pip 19.1.
Therefore, this patch updates the pip version to the last one that works.

The full error message is below.

  $ pip install pandas
  DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
  Collecting pandas
    Using cached https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz
    Installing build dependencies ... done
    Getting requirements to build wheel ... error
    Complete output from command /home/jenkins-slave/a/bin/python3 /home/jenkins-slave/a/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsknqc6o3:
    Traceback (most recent call last):
      File "/home/jenkins-slave/a/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/home/jenkins-slave/a/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/jenkins-slave/a/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
        return hook(config_settings)
      File "/tmp/pip-build-env-z5ha9gs9/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel
        return _get_build_requires(config_settings, requirements=['wheel'])
      File "/tmp/pip-build-env-z5ha9gs9/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires
        _run_setup()
      File "/tmp/pip-build-env-z5ha9gs9/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 85, in _run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 27, in <module>
        import versioneer
    ImportError: No module named 'versioneer'

Change-Id: Iecbc55877e832a0ef437d2799e09c39fb314cb95
Reviewed-on: http://gerrit.cloudera.org:8080/12255
Reviewed-by: Adar Dembo <adar@cloudera.com>
Tested-by: Adar Dembo <adar@cloudera.com>