[thirdparty] fix building LLVM+IWYU on ARM (one more patch)
This is one more patch to fix building IWYU in-tree with LLVM on ARM:
this is a patch [1] from IWYU's upstream repo, with paths modified to
accommodate for the LLVM in-tree layout of the source files.
Without this patch, building Kudu's 3rd-party on ARM after [2]
produced an error like below:

  thirdparty/src/llvm-11.0.0.src/tools/clang/tools/include-what-you-use/iwyu.cc:4142:3: error: ‘LLVMInitializeX86TargetInfo’ was not declared in this scope
     LLVMInitializeX86TargetInfo();

This is a follow-up to [2] and [3].

[1] https://github.com/include-what-you-use/include-what-you-use/commit/0de60d8a2
[2] https://github.com/apache/kudu/commit/6962aa8fb
[3] https://github.com/apache/kudu/commit/de9a0370e

Change-Id: I4628f31c8238f4863b7eb31b888f6dfa595cad17
Reviewed-on: http://gerrit.cloudera.org:8080/22537
Tested-by: Alexey Serbin <alexey@apache.org>
Reviewed-by: Abhishek Chennaka <achennaka@cloudera.com>
(cherry picked from commit 40db16aac4c4028283c9be3bbda655dda0b73dce)
Reviewed-on: http://gerrit.cloudera.org:8080/22540
Reviewed-by: Marton Greber <greber.mx@gmail.com>