[docs] upgrade liquid version
Current docs support scripts use liquid 3.0.6. which can cause the
following error:
  jekyll 3.6.3 | Error:  undefined method `to_date' for Liquid::Utils:Module

Upgrade the versio to be 4.0.0 as suggested in [1].

[1]: https://github.com/poole/hyde/issues/215

Change-Id: Ie5220a888b4bac482f11e908d892f5d3cfc58d3f
Reviewed-on: http://gerrit.cloudera.org:8080/15950
Tested-by: Kudu Jenkins
Reviewed-by: Grant Henke <granthenke@apache.org>